sonar.projectKey=AI-Powered-Mock-Interview-Platform
sonar.projectName=AI-Powered-Mock-Interview-Platform

sonar.sources=client,server

sonar.exclusions=\
**/node_modules/**,\
**/dist/**,\
**/build/**,\
**/.git/**,\
**/coverage/**

sonar.sourceEncoding=UTF-8